language: php

php:
    - 7.3
    - 7.4
    - 8.0
    - nightly

install:
    - composer update --prefer-stable --prefer-dist

script:
    - XDEBUG_MODE=coverage composer test-ci

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml
